name: shop_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  async: ^2.10.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.7
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  dotted_line: ^3.1.0
  equatable: ^2.0.3
  root: ^2.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.7
  flutter_screenutil: ^5.5.3+2
  gap: ^2.0.0
  get_it: ^7.2.0
  hexcolor: ^3.0.1
  encrypt: ^5.0.1
  http: ^0.13.5
  intl: ^0.17.0
  logger: ^1.3.0
  path_provider: ^2.0.14
  mockito: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^10.2.0
  persistent_bottom_nav_bar_v2: ^4.1.11
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.5
  stacked: ^3.2.3
  stacked_hooks: ^0.2.3
  stacked_services: ^1.0.2
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: null
  build_runner: null
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - env/dev.env
    - env/staging.env
    - env/prod.env
    - assets/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
